# Generated by Django 6.0.6 on 2026-06-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='static/uploaded_imgs/')),
                ('files', models.FileField(upload_to='static/uploaded_files/')),
                ('Description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
