# Generated by Django 6.0.6 on 2026-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='static/uploaded_files/'),
        ),
    ]
