# Generated by Django 6.0.6 on 2026-06-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_projects_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
